//  FETCHING SPORTS DATA
export const FETCH_SPORTS = 'FETCH_SPORTS'
export const FETCH_BETS = 'FETCH_BETS'
export const FETCH_ERROR = 'FETCH_ERROR'
export const FETCH_SPORT_TEAM_1 = 'FETCH_SPORT_TEAM_1'
export const FETCH_SPORT_TEAM_2 = 'FETCH_SPORT_TEAM_2'

// UI CONTROLS
export const TOGGLE_UI_CONTAINER1 = 'TOGGLE_UI_CONTAINER1'
export const TOGGLE_UI_CONTAINER2 = 'TOGGLE_UI_CONTAINER2'